name: Update daily dev json from RSS bookmarks

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: I-Valchev/rss-to-json@1.0.0
        with:          
          target: output/feeds.json # An optional parameter to specify the target. Defaults to feeds.json          
          
